### ISSUE TITLE
Cannot find module 'C:\My Data\node-pre-gyp\bin\node-pre-gyp'

### ISSUE THREAD

**Issue by zeealik** [apollographql/fullstack-tutorial#143]
I am following the tutorial from the official site. When I run the below command in terminal.

cd start/server && npm install

it throws error

Error: Cannot find module 'C:\My Data\node-pre-gyp\bin\node-pre-gyp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Link:
https://www.apollographql.com/docs/tutorial/schema/

**Comment by sumitsssss** [comment]
I have the same issue.
