### ISSUE TITLE
[Docs] Issue when publishing schema

### ISSUE THREAD

**Issue by fernando-sendMail** [apollographql/fullstack-tutorial#44]
Hey there!
For some reason when trying to [publish the schema](https://www.apollographql.com/docs/tutorial/production.html#publish) I was getting this error:
```
  ✔ Loading Apollo Project
  ✖ Uploading service to Engine
    → No service found to link to Engine
Error: No service found to link to Engine
    at Task.task (~/.npm/_npx/32532/lib/node_modules/apollo/lib/commands/service/push.js:17:31)
    at Promise.resolve.then.then.skipped (~/.npm/_npx/32532/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
    at <anonymous>
```

This is what I did, and didn't work:
- Had my `.env` file with the `ENGINE_API_KEY` set.
- Tried removing the `sevice:` prefix from the value of the variable
- Tried restarting the server
- Tried running `npx apollo service:check && npx apollo service:push` from the `/server` folder
- Double and tripled checked the API key

Finally I gave up and had to type the parameters directly on the `service:push` command.

Is this only my issue?

**Comment by agur** [comment]
any news on this one?

**Comment by GhassenRjab** [comment]
I had the same error as you. I figured out I was in the wrong directory

**Comment by iancrowther** [comment]
ha ha.. thanks @GhassenRjab - I was in the wring dir also!! D'oh!

**Comment by JWTappert** [comment]
I was getting the same error as you as well and I made sure I was in the correct directory and everything. 

I fixed the issue by closing my terminals in VS code and using a fresh iterm. Deploying the service worked using the commands from the documentation.
