### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markMutationError' of undefined

### ISSUE THREAD

**Issue by lawrenceforsytheiii** [apollographql/fullstack-tutorial#50]
This issue should be logged here as it has to do with this tutorial. Specifically deploying the server portion using Zeit Now v1 instead of v2: https://github.com/apollographql/apollo-client/issues/4166

**Comment by pyramation** [comment]
running into the same issue

**Comment by hammer3** [comment]
Me too.
The login works with the daisy@apollographql.com user from the tutorial. Maybe because the login was done before the deployment to NOW.
If I use a new user I get the following Error:
   "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "name": "SequelizeDatabaseError",
          "parent": {
            "errno": 8,
            "code": "SQLITE_READONLY",
            "sql": "INSERT INTO `users` (`id`,`createdAt`,`updatedAt`,`email`) VALUES (NULL,'2019-01-03 12:16:06.503 +00:00','2019-01-03 12:16:06.503 +00:00','Max.Muster@gmail.com');"
          },
          "original": {
            "errno": 8,
            "code": "SQLITE_READONLY",
            "sql": "INSERT INTO `users` (`id`,`createdAt`,`updatedAt`,`email`) VALUES (NULL,'2019-01-03 12:16:06.503 +00:00','2019-01-03 12:16:06.503 +00:00','Max.Muster@gmail.com');"
          },
          "sql": "INSERT INTO `users` (`id`,`createdAt`,`updatedAt`,`email`) VALUES (NULL,'2019-01-03 12:16:06.503 +00:00','2019-01-03 12:16:06.503 +00:00','Max.Muster@gmail.com');",
          "stacktrace": [
            "SequelizeDatabaseError: SQLITE_READONLY: attempt to write a readonly database",
            "    at Query.formatError (/home/nowuser/src/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)",
            "    at Statement.afterExecute (/home/nowuser/src/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)",
            "    at Statement.replacement (/home/nowuser/src/node_modules/sqlite3/lib/trace.js:19:31)"
          ]
