### ISSUE TITLE
querying `launches` returns errors on "final" repo.

### ISSUE THREAD

**Issue by corpetty** [apollographql/fullstack-tutorial#79]
It seems the tutorial is out of date, as even the final returns errors, so I know it isn't with my implementation after going through the tutorial.

The playground returns the following after running the `GetLaunches` query from the tutorial:

```
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"id\" on type \"LaunchConnection\".",
        "locations": [
          {
            "line": 3,
            "column": 5
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"id\" on type \"LaunchConnection\".",
              "    at Object.Field (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:64:31)",
              "    at Object.enter (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/language/visitor.js:333:29)",
              "    at Object.enter (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/language/visitor.js:384:25)",
              "    at visit (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/language/visitor.js:251:26)",
              "    at Object.validate (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/validation/validate.js:63:22)",
              "    at validate (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/apollo-server-core/dist/requestPipeline.js:172:32)",
              "    at Object.<anonymous> (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/apollo-server-core/dist/requestPipeline.js:113:38)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      },
      {
        "message": "Cannot query field \"mission\" on type \"LaunchConnection\".",
        "locations": [
          {
            "line": 4,
            "column": 5
          }
        ],
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Cannot query field \"mission\" on type \"LaunchConnection\".",
              "    at Object.Field (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:64:31)",
              "    at Object.enter (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/language/visitor.js:333:29)",
              "    at Object.enter (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/language/visitor.js:384:25)",
              "    at visit (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/language/visitor.js:251:26)",
              "    at Object.validate (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/graphql/validation/validate.js:63:22)",
              "    at validate (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/apollo-server-core/dist/requestPipeline.js:172:32)",
              "    at Object.<anonymous> (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/apollo-server-core/dist/requestPipeline.js:113:38)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/home/petty/Github/apollo-graphql/fullstack-tutorial/final/server/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by corpetty** [comment]
versions:
- npm: 6.4.1
- node: 10.15.3

**Comment by logusgraphics** [comment]
You must do the query as follows:

```gql
query GetLaunches {
  launches {
    launches {
      id
      mission {
        name
      }
    }
  }
}
```

**Comment by aphex-** [comment]
Can not confirm that the query mentioned by @logusgraphics works. I get this error then:
`{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field LaunchConnection.launches.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "launches",
        "launches"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field LaunchConnection.launches.",
            "    at completeValue (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:596:13)",
            "    at completeValueCatchingError (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:531:19)",
            "    at resolveField (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:471:10)",
            "    at executeFields (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:311:18)",
            "    at collectAndExecuteSubfields (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:747:10)",
            "    at completeObjectValue (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:737:10)",
            "    at completeValue (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:626:12)",
            "    at completeValue (/Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:593:21)",
            "    at /Users/luca/repo/appolo/fullstack-tutorial/start/server/node_modules/graphql/execution/execute.js:528:16",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null
}`

**Comment by aphex-** [comment]
The error mentioned by @corpetty is happening to me if I try the steps in [run-queries-in-the-playground](https://www.apollographql.com/docs/tutorial/resolvers/#run-queries-in-the-playground) before adding [Paginated queries](https://www.apollographql.com/docs/tutorial/resolvers/#paginated-queries) to the resolver.

**Comment by MarcioDev86** [comment]
Same here, this tutorial doesn't work...

**Comment by deolaolalere** [comment]
same here it doesn't wok

**Comment by AlbertWhite** [comment]
It doesn't work with this error to me.
![image](https://user-images.githubusercontent.com/9461930/67874495-47ec0780-fb35-11e9-9b1d-4c7a96bde8f0.png)

**Comment by hafidaEL** [comment]
the query (with pagination) doesn't work only in the playground. 
 But it works perfectly in others clients (Apollo Client / React,  apollo studio ...)
